upstream finpath_frontend_dev {
    server frontend-web-dev:80;
}

server {
    listen 80;
    server_name dev.css-appli24.com;

    location / {
        proxy_pass http://finpath_frontend_dev;
    }
}