worker_processes  1;

events {
  worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout  65;

  # PROD Upstreams
  upstream finpath_frontend_prod {
    server finpath-frontend-web-prod:80;
  }

  upstream finpath_backend_prod {
    server finpath-backend-prod:9080;
  }

  # DEV Upstreams
  upstream finpath_frontend_dev {
    server finpath-frontend-web-dev:80;
  }

  upstream finpath_backend_dev {
    server finpath-backend-dev:9080;
  }

  # ===== PROD DOMAIN =====
  server {
    listen 80;
    server_name css-appli24.com;

    location / {
      proxy_pass         http://finpath_frontend_prod;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;
      try_files $uri $uri/ /index.html;
    }

    location /api/ {
      proxy_pass         http://finpath_backend_prod/; # ggf. Kontext anpassen
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;
    }
  }

  # ===== DEV DOMAIN =====
  server {
    listen 80;
    server_name dev.css-appli24.com;

    location / {
      proxy_pass         http://finpath_frontend_dev;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;
      try_files $uri $uri/ /index.html;
    }

    location /api/ {
      proxy_pass         http://finpath_backend_dev/; # ggf. Kontext anpassen
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;
    }
  }
}