server {
    listen 80;
    server_name css-appli24.com;

    # API Routing
    location /api/ {
        proxy_pass http://finpath-backend-dev:9080;
        proxy_set_header Host $host;
    }

    # Frontend Routing
    location / {
        proxy_pass http://finpath-frontend-web-dev:80;
        proxy_set_header Host $host;
    }
}