services:
  db:
    image: postgres:16
    env_file: ./secrets/.env.dev
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build:
      context: ../finpath-backend
      dockerfile: Dockerfile
    image: ghcr.io/janishuber/finpath-backend:latest
    env_file: ./secrets/.env.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports: ["9080:9080"]
    depends_on: [ db ]

  frontend:
    build:
      context: ../apps/finpath-frontend-web
      dockerfile: Dockerfile
    image: ghcr.io/janishuber/finpath-frontend-web:latest
    ports: ["8080:80"]
    depends_on: [ backend ]

volumes:
  db_data: