services:
  db-dev:
    image: postgres:16
    container_name: finpath-db-dev
    env_file: ./secrets/.env.db.dev
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - finpath-net
    restart: always

  backend-dev:
    image: ghcr.io/janishuber/finpath-backend:dev
    container_name: finpath-backend-dev
    env_file: ./secrets/.env.dev
    environment:
      DB_HOST: db-dev
      DB_PORT: 5432
    expose:
      - "10080:9080"
    depends_on:
      - db-dev
    networks:
      - finpath-net
    restart: always

  frontend-web-dev:
    image: ghcr.io/janishuber/finpath-frontend-web:dev
    container_name: finpath-frontend-web-dev
    expose:
      - "8080:80"
    depends_on:
      - backend-dev
    networks:
      - finpath-net
    restart: always

volumes:
  db_data_dev:

networks:
  finpath-net:
    external: true