services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  backend:
    image: ghcr.io/janishuber/finpath-backend:latest
    depends_on: [ db ]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "9080:9080"

  frontend:
    image: ghcr.io/janishuber/finpath-frontend:latest
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data: