services:
  backend-dev:
    image: ghcr.io/janishuber/finpath-backend:dev
    container_name: finpath-backend-dev
    env_file: ./environments/dev.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    expose:
      - "9080"
    networks:
      - finpath-net
    restart: always

  frontend-web-dev:
    image: ghcr.io/janishuber/finpath-frontend-web:dev
    container_name: finpath-frontend-web-dev
    expose:
      - "80"
    depends_on:
      - backend-dev
    networks:
      - finpath-net
    restart: always

networks:
  finpath-net:
    external: true
