services:
  backend-prod:
    image: ghcr.io/janishuber/finpath-backend:prod
    container_name: finpath-backend-prod
    env_file: ./environments/prod.env
    environment:
      SPRING_PROFILES_ACTIVE: prd
    expose:
      - "9080"
    networks:
      - finpath-net
    restart: always

  frontend-web-prod:
    image: ghcr.io/janishuber/finpath-frontend-web:prod
    container_name: finpath-frontend-web-prod
    expose:
      - "80"
    networks:
      - finpath-net
    restart: always

networks:
  finpath-net:
    external: true
