name: Build & Publish (prod)

on:
  push:
    branches: [ "prod" ]

concurrency:
  group: build-publish-prod
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/finpath

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Build backend WAR (Maven)
        run: mvn -B -q -DskipTests clean package --file finpath-backend/pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------- BACKEND META & BUILD --------
      - name: Meta (backend)
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_PREFIX }}-backend
          tags: |
            type=raw,value=latest
            type=sha
          labels: |
            org.opencontainers.image.title=finpath-backend
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build & Push (backend)
        id: build_backend
        uses: docker/build-push-action@v6
        with:
          context: ./finpath-backend
          file: ./finpath-backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend
          provenance: mode=min

      # -------- FRONTEND META & BUILD --------
      - name: Meta (frontend)
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_PREFIX }}-frontend
          tags: |
            type=raw,value=latest
            type=sha
          labels: |
            org.opencontainers.image.title=finpath-frontend
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build & Push (frontend)
        id: build_frontend
        uses: docker/build-push-action@v6
        with:
          context: ./finpath-frontend
          file: ./finpath-frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend
          provenance: mode=min

      # -------- ATTESTATIONS --------
      - name: Attest backend image
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.IMAGE_PREFIX }}-backend
          subject-digest: ${{ steps.build_backend.outputs.digest }}
          push-to-registry: true

      - name: Attest frontend image
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.IMAGE_PREFIX }}-frontend
          subject-digest: ${{ steps.build_frontend.outputs.digest }}
          push-to-registry: true